[build-system]
requires = ["setuptools>=70.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "air_control"
version = "0.0.1"
authors = [
  { name="lombo-cmyk"},
]
readme = "README.md"
requires-python = ">=3.8"